# Generated by Django 3.2.2 on 2021-05-11 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20210511_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='awayTeam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='away_teams', to='games.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='homeTeam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='home_teams', to='games.team'),
            preserve_default=False,
        ),
    ]
