# Generated by Django 3.2.2 on 2021-05-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('homeTeamScore', models.IntegerField(default=0)),
                ('awayTeamScore', models.IntegerField(default=0)),
                ('final', models.BooleanField(default=False)),
                ('period', models.TextField()),
            ],
        ),
    ]
