# Generated by Django 3.2.2 on 2021-05-26 14:18

from django.db import migrations, models
import django.utils.timezone
import games.validators


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_apirequest_requester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='start',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='game',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='period',
            field=models.TextField(validators=[games.validators.validate_period]),
        ),
    ]
