# Generated by Django 3.2.2 on 2021-06-18 04:01

from django.db import migrations, models
import django.db.models.deletion
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_season_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(default=games.models.Season.current_season_id, on_delete=django.db.models.deletion.CASCADE, to='games.season'),
        ),
    ]
