# Generated by Django 3.2.2 on 2021-07-17 16:46

from django.db import migrations, models
import django.db.models.deletion
import games.validators


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, validators=[games.validators.validate_event_type])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('primary_assister', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_assisters', to='games.player')),
                ('scorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorers', to='games.player')),
                ('secondary_assister', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_assisters', to='games.player')),
            ],
        ),
    ]
